### PR TITLE
Update to Discord V14

### PR DESCRIPTION
**Pull request by mazkdevf**
Decided to Update the bot to the Latest Discord.JS Version out there currently, 
Bot Requires: `Node 16.9 / + to Run`

Also changed Config `devserverid` to `DevelopmentServerId`

**Why not directly on the Repository?**
Because i want to let other **KeyAuth Management** and also **Founder** know about this. And they can look into it and if they accept / like **it**, it will be Pushed to the `Main-Branch` of this **Repository**

**Best Regards
KeyAuth Head Admin / Developer mazkdevf.**

### CODE REVIEW

**Comment by mazkdevf** [comment]
don't merge yet, i will add smth to it

**Comment by wnelson03** [comment]
ok

**Comment by mazkdevf** [comment]
> ok

Okay now you can update it

**Comment by wnelson03** [comment]
Thank you.

**Pull request merged**
