### PR TITLE
.

### PR DESCRIPTION
**Pull request by TheHellTower**
You should avoid using 2 ways for configuration.

`.env` files are not really hard to use and preferred.

### CODE REVIEW

**Comment by faintastic** [comment]
The code already has functionality for a .env config type.

**Review by faintastic — COMMENTED** [review]
Code already has functionality for .env files aswell as .json files

**Comment by TheHellTower** [comment]
> Code already has functionality for .env files aswell as .json files

You didn't read what was wrote on the first line of [this](https://github.com/KeyAuth/KeyAuth-Discord-Bot/pull/16#issue-2162148870) or you didn't get it ?

**Comment by faintastic** [comment]
I did read it, but because it is preferred doesn't mean someone doesn't want to use the .json format. Why remove code that isn't bothering anyone. Someone may prefer .json config files more.

**Comment by faintastic** [comment]
But it doesn't affect anything having both of them.

**Comment by TheHellTower** [comment]
> I did read it, but because it is preferred doesn't mean someone doesn't want to use the .json format. Why remove code that isn't bothering anyone. Someone may prefer .json config files more.

For security it's better for security if for example you use repl.it or things like this to host than a `.json` file.
Also it's useless to have 2 ways to do configuration you have to make a choice for it to be logical otherwise there are users that might fill both whatever what is wrote on the README since you might now that not everyone are able to completely read a README.

**Comment by faintastic** [comment]
For security sure, but if you are hosting it on replit, just use the .env file and don't use the .json file? It's not useless, it's the users choice on which config file they would rather use. To even know how the config files work, they would have to read the README, due to the fact that they have to rename the files for either of them to work (unless they know what they are doing).

**Comment by faintastic** [comment]
And if they fill out both, it isn't going to change anything, it's a small oops that doesn't change anything.

**Comment by TheHellTower** [comment]
> For security sure, but if you are hosting it on replit, just use the .env file and don't use the .json file? It's not useless, it's the users choice on which config file they would rather use. To even know how the config files work, they would have to read the README, due to the fact that they have to rename the files for either of them to work (unless they know what they are doing).

It is useless..
Also it's not that hard to fill both of them and `.env` is harder to break than `.json` when we see that `"` are not necessarily required in `.env` and I seen many users breaks `.json` files just for one of these.

**Comment by faintastic** [comment]
My point is still standing, it's the user's choice to which configuration type they would like to use. If they want to use .env it's already integrated, if they want to use .json it's already integrated.

If someone chooses .json format, you'd think they know how to not break it?

**Comment by TheHellTower** [comment]
> My point is still standing, it's the user's choice to which configuration type they would like to use. If they want to use .env it's already integrated, if they want to use .json it's already integrated.

Well okay I understood it's waste of time to talk with you keep both it's useless af.

**Pull request closed without merging**
